DROP TABLE IF EXISTS film;
DROP TABLE IF EXISTS director;

CREATE TABLE IF NOT EXISTS Director (
	id SERIAL PRIMARY KEY,
	first_name VARCHAR NOT NULL,
	last_name VARCHAR NOT NULL,
	birth_date DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS Film (
	id SERIAL PRIMARY KEY,
	director_id INT REFERENCES director (id) ON DELETE CASCADE,
	name VARCHAR NOT NULL,
	release_date DATE NOT NULL,
	genre VARCHAR NOT NULL
);